version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tournly-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tournly
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: tournly
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: tournly-pgadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@tournly.dev
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
